# UTF-8

module Dea
  class MsgType
    ONDEMAND_MSG ="ONDEMAND_MSG"
    DEPENDENCE_MSG ="DEPENDENCE_MSG"
    NEGOTIATION_MSG = "NEGOTIATION_MSG"
    REMOTE_CONF_MSG = "REMOTE_CONF_MSG"
    
    EXPERIMENT_MSG = "EXPERIMENT_MSG"
    
  end
end