# UTF-8

module Dea
  class BufferEventType
    NORMAL = "NORMAL"
    ONDEMAND = "ONDEMAND"
    VALIDTOFREE = "VALIDTOFREE"
    WAITFORREMOTEUPDATE = "WAITFORREMOTEUPDATE"
    #Dea::BufferEventType::WAITFORRMOTEUPDATE
    EXEUPDATE ="EXEUPDATE"
    DEFREEZE="DEFREEZE"
  end
end