# coding: UTF-8

require "steno"
require "steno/core_ext"

module Dea
  class DepOperationType
    
    ACK_SUBTX_INIT = "ACK_SUBTX_INIT"
    NOTIFY_SUBTX_END = "NOTIFY_SUBTX_END"
    NOTIFY_ROOT_TX_END ="NOTIFY_ROOT_TX_END"
    NOTIFY_START_REMOTE_SUB_TX="NOTIFY_START_REMOTE_SUB_TX"
#     DepOperationType::NOTIFY_START_REMOTE_SUB_TX
    
    
    NOTIFY_FUTURE_CREATE="NOTIFY_FUTURE_CREATE"
    ACK_FUTURE_CREATE="ACK_FUTURE_CREATE"    
    NOTIFY_FUTURE_REMOVE="NOTIFY_FUTURE_REMOVE"
    
    NOTIFY_PAST_CREATE="NOTIFY_PAST_CREATE"
    NOTIFY_PAST_REMOVE="NOTIFY_PAST_REMOVE"
    
    REQ_ONDEMAND_SETUP="REQ_ONDEMAND_SETUP"
    CONFIRM_ONDEMAND_SETUP="CONFIRM_ONDEMAND_SETUP"
    
    NOTIFY_FUTURE_ONDEMAND="NOTIFY_FUTURE_ONDEMAND"
    NOTIFY_PAST_ONDEMAND="NOTIFY_PAST_ONDEMAND"
    
    NOTIFY_SUB_FUTURE_ONDEMAND="NOTIFY_SUB_FUTURE_ONDEMAND"
    NOTIFY_SUB_PAST_ONDEMAND="NOTIFY_SUB_PAST_ONDEMAND"
    
    ACK_FUTURE_ONDEMAND="ACK_FUTURE_ONDEMAND"
    ACK_PAST_ONDEMAND="ACK_PAST_ONDEMAND"
    
    ACK_SUB_FUTURE_ONDEMAND="ACK_SUB_FUTURE_ONDEMAND"
    ACK_SUB_PAST_ONDEMAND="ACK_SUB_PAST_ONDEMAND"
    
    NOTIFY_REMOTE_UPDATE_DONE="NOTIFY_REMOTE_UPDATE_DONE"
    
     
  end
end