# UTF-8

module Dea
  class UpdateContextPayload
    OPERATION_TYPE ="OPERATION_TYPE"
    COMP_IDENTIFIER = "COMP_IDENTIFIER"
    BASE_DIR ="BASE_DIR"
    CLASS_FILE_PATH ="CLASS_FILE_PATH"
    #CONTRIBUTION_URI = "CONTRIBUTION_URI"
    COMPOSITE_URI = "COMPOSITE"
    SCOPE = "SCOPE"
  end
end