# UTF-8
module Dea
  class UpdateOperationType
    ONDEMAND = "ONDEMAND"
    UPDATE = "UPDATE"
    QUERY = "QUERY"
    NOTIFY_UPDATE_IS_DONE_EXP = "NOTIFY_UPDATE_IS_DONE"
    GET_EXECUTION_ENDTIME = "GET_EXECUTION_ENDTIME"
    GET_UPDATE_ENDTIME = "GET_UPDATE_ENDTIME"
    NOTIFY_COORDINATION_TRANQUILLITY_EXP = "NOTIFY_COORDINATION_TRANQUILLITY_EXP"
  end
end